apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: infra
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: infra
spec:
  replicas: 3

