apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - local-pv.yaml
  - metallb-ip-pool.yaml
  - ingress-nginx-lb.yaml

labels:
  - pairs:
      app.kubernetes.io/environment: dev
