apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico-cni-token-refresher
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: calico-cni-token-refresher
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  resourceNames:
  - calico-cni-plugin
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  resourceNames:
  - calico-cni-plugin
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: calico-cni-token-refresher
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: calico-cni-token-refresher
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: calico-cni-token-refresher
---
apiVersion: v1
kind: Secret
metadata:
  name: calico-cni-token-refresher-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: calico-cni-token-refresher
type: kubernetes.io/service-account-token
