apiVersion: v1
kind: Secret
metadata:
  name: harbor-robot-cicd
  namespace: default
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {"auths":{"10.111.111.72":{"username":"robot$ci-cd","password":"BNg1mh1HphgxhtUydyUDANaNbemZCHzB"}}}
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-robot-dis
  namespace: default
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {"auths":{"10.111.111.72":{"username":"robot$dis","password":"7QQnDQ0yY11fY99iLz4xtocW0MMhYUnC"}}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterlab-teradata20
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterlab-teradata20
  template:
    metadata:
      labels:
        app: jupyterlab-teradata20
    spec:
      imagePullSecrets:
      - name: harbor-robot-cicd
      containers:
      - name: app
        image: 10.111.111.72/library/jupyterlab-teradata20:1.9
        imagePullPolicy: Always
        command: ["/bin/sh","-c","sleep 36000"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterlab-extensions
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterlab-extensions
  template:
    metadata:
      labels:
        app: jupyterlab-extensions
    spec:
      imagePullSecrets:
      - name: harbor-robot-cicd
      containers:
      - name: app
        image: 10.111.111.72/library/teradata/jupyterlab-extensions:4.0.2
        imagePullPolicy: Always
        command: ["/bin/sh","-c","sleep 36000"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupter-teradata-fss
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupter-teradata-fss
  template:
    metadata:
      labels:
        app: jupter-teradata-fss
    spec:
      imagePullSecrets:
      - name: harbor-robot-dis
      containers:
      - name: app
        image: 10.111.111.72/dis/jupter-teradata-fss:0.0.1
        imagePullPolicy: Always
        command: ["/bin/sh","-c","sleep 36000"]

