apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterlab-teradata20
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterlab-teradata20
  template:
    metadata:
      labels:
        app: jupyterlab-teradata20
    spec:
      containers:
      - name: app
        image: ghcr.io/k8s-fss/jupyterlab-teradata20:1.9
        imagePullPolicy: Always
        command: ["/bin/sh","-c","sleep 36000"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterlab-extensions
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterlab-extensions
  template:
    metadata:
      labels:
        app: jupyterlab-extensions
    spec:
      containers:
      - name: app
        image: ghcr.io/k8s-fss/jupyterlab-extensions:4.0.2
        imagePullPolicy: Always
        command: ["/bin/sh","-c","sleep 36000"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupter-teradata-fss
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupter-teradata-fss
  template:
    metadata:
      labels:
        app: jupter-teradata-fss
    spec:
      containers:
      - name: app
        image: ghcr.io/k8s-fss/jupter-teradata-fss:0.0.1
        imagePullPolicy: Always
        command: ["/bin/sh","-c","sleep 36000"]
