apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - dis-app.yaml
  - dynamic-routing.yaml
  - fss-dis-frontend-subpath-ingress.yaml
  - headlamp-ingress.yaml
  - mongodb-secret.yaml
  - mongodb.yaml
  - redis-secret.yaml
  - redis.yaml
