apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-fss-dev-mongo-data
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: infra
    name: mongo-data-mongo-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-worker-2
  hostPath:
    path: /var/lib/fss-dis-platform/pv/fss-mongo-data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-fss-dev-redis-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: infra
    name: redis-data-redis-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-worker-2
  hostPath:
    path: /var/lib/fss-dis-platform/pv/fss-redis-data
    type: DirectoryOrCreate
